### ISSUE TITLE
config should return undefined when object has no keys

### ISSUE THREAD

**Issue by jetersen** [probot/octokit-plugin-config#41]
Inside a custom default the config object can be `{}` when `_extends` is used.

```yaml
_extends: base:test.yaml
```

To workaround it, you need to write something like this:
```javascript
  configs
    .map(config => {
      let labels = config.labels ? config.labels : config;
      if (Object.keys(labels).length === 0) labels = undefined
      return {labels: labels || []};
    })
```

if you returned `undefined` after deleting the `_extends` key that would make it easier to merge objects.

**Comment by gr2m** [comment]
I think the `config` should always be an object, so you don't need to add a check every time you want to read any `config` property. You would need to change your code above to

```javascript
  configs
    .map(config => {
      if (!config) return { labels: [] }
      return { labels: config.labels ? config.labels : config };
    })
```

I don't think that would be much better? Or am I missing something?

**Comment by jetersen** [comment]
You can see my use over here btw: https://github.com/crazy-max/ghaction-github-labeler/pull/125

**Comment by jetersen** [comment]
Your above example does not work, the test in the PR validates issue.

**Comment by jetersen** [comment]
I think this: https://github.com/probot/octokit-plugin-config/blob/3975be288f0a70b5bc747da7565868b0cb6f4db2/src/util/get-config-files.ts#L66-L67

Could be written as
```javascript
  delete requestedRepoFile.config._extends; 
  const files = []; 
  if (Object.keys(requestedRepoFile).length !== 0) {
    files.push(requestedRepoFile)
  }
```

**Comment by gr2m** [comment]
It makes more sense, this is a custom merge strategy using the `defaults` option. I think your use case is easy enough to workaround, and in theory there might be a use case when an empty configuration might be significant. I think the current behavior is easier to understand, removing a config object from the array just because it doesn't have any configuration in it might lead to to unpredictable, hard to debug bugs. I'd prefer to leave it as is, sorry

**Comment by jetersen** [comment]
No worries.
